-- =====================================================================
-- 食べログ 百名店（ラーメン）の一覧（2026-09-19）
-- =====================================================================
-- 「今後行きたい店」の台帳。まずは ラーメン TOKYO 百名店 2025（2025-12-02発表・
-- 100店）を入れる。/ramen で ramen_logs.tabelog_shop_url の店IDと突き合わせ、
-- 「行った／まだ」を出す（2026-09-19 時点で訪問済み9店・未訪問91店）。
--
-- 出典は award.tabelog.com の一覧ページで、持つのは店名・最寄り駅・定休日・
-- 店ページURLの事実だけ（点数や本文は持たない）。
-- 百名店は順位表ではないので list_order は「一覧ページの掲載順」にすぎない。
--
-- rollback: DROP TABLE public.tabelog_hyakumeiten;
CREATE TABLE IF NOT EXISTS public.tabelog_hyakumeiten (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  edition          text        NOT NULL,   -- 例: ramen_tokyo_2025
  list_order       integer     NOT NULL,   -- 一覧ページの掲載順（順位ではない）
  shop             text        NOT NULL,
  station          text,                   -- 最寄り駅。無い店は市区名（例: 府中市）
  holiday          text,                   -- 定休日。一覧に無ければ null
  tabelog_url      text        NOT NULL,
  tabelog_shop_id  text        NOT NULL,   -- URL末尾の数字。ramen_logs との突き合わせ鍵
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (edition, tabelog_shop_id)
);

COMMENT ON TABLE public.tabelog_hyakumeiten IS
  '食べログ百名店の一覧。edition ごとに100店。ramen_logs とは tabelog_shop_id で突き合わせる';

-- 他のラーメン系テーブルと同じく、読みは anon に開き、書きは service role だけ
-- （アプリは合言葉認証の内側から anon キーで読む）。
ALTER TABLE public.tabelog_hyakumeiten ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tabelog_hyakumeiten anon read" ON public.tabelog_hyakumeiten
  AS PERMISSIVE FOR SELECT TO anon, authenticated USING (true);
